"""
Paper Analysis Model

Represents the structured analysis generated by the
Paper Analysis Agent.
"""


class PaperAnalysis:

    def __init__(
        self,
        title,
        authors,
        year,
        citation_count,
        summary,
        keywords,
        research_area
    ):

        self.title = title
        self.authors = authors
        self.year = year
        self.citation_count = citation_count
        self.summary = summary
        self.keywords = keywords
        self.research_area = research_area

    def to_dict(self):
        """
        Convert object into dictionary.
        """

        return {
            "title": self.title,
            "authors": self.authors,
            "year": self.year,
            "citation_count": self.citation_count,
            "summary": self.summary,
            "keywords": self.keywords,
            "research_area": self.research_area
        }