"""
DOCX Generator Utility

Purpose:
Generate a Microsoft Word (.docx) version
of the research report.
"""

import os
from datetime import datetime
from docx import Document
from docx.shared import Pt


def generate_docx(
    report: dict,
    output_dir: str = "generated_reports"
):
    """
    Generate a DOCX research report.

    Returns:
        Path of generated DOCX file.
    """

    os.makedirs(output_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    filename = os.path.join(
        output_dir,
        f"Research_Report_{timestamp}.docx"
    )

    document = Document()

    # ----------------------------
    # Title
    # ----------------------------

    title = document.add_heading(
        "Research Analysis Report",
        level=1
    )

    title.runs[0].font.size = Pt(22)

    # ----------------------------
    # Basic Information
    # ----------------------------

    document.add_heading(
        "Basic Information",
        level=2
    )

    document.add_paragraph(
        f"Research Topic: {report.get('research_topic','')}"
    )

    document.add_paragraph(
        f"Generated By: {report.get('generated_by','')}"
    )

    document.add_paragraph(
        f"Generated At: {report.get('generated_at','')}"
    )

    document.add_paragraph(
        f"Total Papers: {report.get('total_papers',0)}"
    )

    # ----------------------------
    # Executive Summary
    # ----------------------------

    document.add_heading(
        "Executive Summary",
        level=2
    )

    document.add_paragraph(
        report.get(
            "executive_summary",
            ""
        )
    )

    # ----------------------------
    # Literature Review
    # ----------------------------

    document.add_heading(
        "Literature Review",
        level=2
    )

    literature = report.get(
        "literature_review",
        {}
    )

    if isinstance(literature, dict):

        for key, value in literature.items():

            document.add_heading(
                key.replace("_", " ").title(),
                level=3
            )

            document.add_paragraph(str(value))

    # ----------------------------
    # Methodology Comparison
    # ----------------------------

    document.add_heading(
        "Methodology Comparison",
        level=2
    )

    comparison = report.get(
        "methodology_comparison",
        {}
    ).get(
        "comparison_summary",
        {}
    )

    for key, value in comparison.items():

        document.add_paragraph(
            f"{key.replace('_',' ').title()}: {value}"
        )

    # ----------------------------
    # Research Gap
    # ----------------------------

    document.add_heading(
        "Research Gap Analysis",
        level=2
    )

    gap = report.get(
        "research_gap",
        {}
    ).get(
        "summary",
        {}
    )

    for key, value in gap.items():

        document.add_paragraph(
            f"{key.replace('_',' ').title()}: {value}"
        )

    # ----------------------------
    # Experiment Plan
    # ----------------------------

    document.add_heading(
        "Experiment Plan",
        level=2
    )

    experiment = report.get(
        "experiment_plan",
        {}
    )

    for key, value in experiment.items():

        document.add_paragraph(
            f"{key.replace('_',' ').title()}: {value}"
        )

    # ----------------------------
    # Report Summary
    # ----------------------------

    document.add_heading(
        "Report Summary",
        level=2
    )

    summary = report.get(
        "report_summary",
        {}
    )

    for key, value in summary.items():

        document.add_paragraph(
            f"{key.replace('_',' ').title()}: {value}"
        )

    # ----------------------------
    # Conclusion
    # ----------------------------

    document.add_heading(
        "Conclusion",
        level=2
    )

    document.add_paragraph(
        report.get(
            "conclusion",
            ""
        )
    )

    document.save(filename)

    return filename