"""
Markdown Generator Utility

Purpose:
Generate a Markdown (.md) version
of the research report.
"""

import os
from datetime import datetime

def generate_markdown(
    report: dict,
    output_dir: str = "generated_reports"
):
    """
    Generate a Markdown research report.

    Returns:
        Path of generated Markdown file.
    """

    os.makedirs(output_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    filename = os.path.join(
        output_dir,
        f"Research_Report_{timestamp}.md"
    )

    with open(
        filename,
        "w",
        encoding="utf-8"
    ) as file:

        file.write("# Research Analysis Report\n\n")

        file.write(
            f"**Research Topic:** {report.get('research_topic','')}\n\n"
        )

        file.write(
            f"**Generated By:** {report.get('generated_by','')}\n\n"
        )

        file.write(
            f"**Generated At:** {report.get('generated_at','')}\n\n"
        )

        file.write(
            f"**Total Papers:** {report.get('total_papers',0)}\n\n"
        )

        file.write("## Executive Summary\n\n")

        file.write(
            report.get(
                "executive_summary",
                ""
            )
        )

        file.write("\n\n")

        # ------------------------------------

        file.write("## Literature Review\n\n")

        literature = report.get(
            "literature_review",
            {}
        )

        if isinstance(literature, dict):

            for key, value in literature.items():

                file.write(
                    f"### {key.replace('_',' ').title()}\n\n"
                )

                file.write(
                    f"{value}\n\n"
                )

        # ------------------------------------

        file.write("## Methodology Comparison\n\n")

        comparison = report.get(
            "methodology_comparison",
            {}
        ).get(
            "comparison_summary",
            {}
        )

        for key, value in comparison.items():

            file.write(
                f"- **{key.replace('_',' ').title()}**: {value}\n"
            )

        file.write("\n")

        # ------------------------------------

        file.write("## Research Gap Analysis\n\n")

        gap = report.get(
            "research_gap",
            {}
        ).get(
            "summary",
            {}
        )

        for key, value in gap.items():

            file.write(
                f"- **{key.replace('_',' ').title()}**: {value}\n"
            )

        file.write("\n")

        # ------------------------------------

        file.write("## Experiment Plan\n\n")

        experiment = report.get(
            "experiment_plan",
            {}
        )

        for key, value in experiment.items():

            file.write(
                f"### {key.replace('_',' ').title()}\n\n"
            )

            file.write(
                f"{value}\n\n"
            )

        # ------------------------------------

        file.write("## Report Summary\n\n")

        summary = report.get(
            "report_summary",
            {}
        )

        for key, value in summary.items():

            file.write(
                f"- **{key.replace('_',' ').title()}**: {value}\n"
            )

        file.write("\n")

        # ------------------------------------

        file.write("## Conclusion\n\n")

        file.write(
            report.get(
                "conclusion",
                ""
            )
        )

    return filename