"""
PDF Generator Utility

Purpose:
Generate a PDF version of the final research report.
"""

import os
from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

styles = getSampleStyleSheet()


def add_section(elements, title, data):

    elements.append(
        Paragraph(f"<b>{title}</b>", styles["Heading2"])
    )
    elements.append(Spacer(1, 6))

    if isinstance(data, dict):

        for key, value in data.items():

            if isinstance(value, list):

                elements.append(
                    Paragraph(
                        f"<b>{key.replace('_', ' ').title()}</b>",
                        styles["Heading3"],
                    )
                )

                if value:
                    for item in value:
                        elements.append(
                            Paragraph(
                                f"• {item}",
                                styles["BodyText"],
                            )
                        )
                else:
                    elements.append(
                        Paragraph(
                            "None",
                            styles["BodyText"],
                        )
                    )

                elements.append(Spacer(1, 4))

            elif isinstance(value, dict):

                elements.append(
                    Paragraph(
                        f"<b>{key.replace('_', ' ').title()}</b>",
                        styles["Heading3"],
                    )
                )

                for k, v in value.items():

                    elements.append(
                        Paragraph(
                            f"{k}: {v}",
                            styles["BodyText"],
                        )
                    )

                elements.append(Spacer(1, 4))

            else:

                elements.append(
                    Paragraph(
                        f"<b>{key.replace('_', ' ').title()}:</b> {value}",
                        styles["BodyText"],
                    )
                )

    elif isinstance(data, list):

        if data:

            for item in data:
                elements.append(
                    Paragraph(
                        f"• {item}",
                        styles["BodyText"],
                    )
                )

        else:

            elements.append(
                Paragraph(
                    "None",
                    styles["BodyText"],
                )
            )

    else:

        elements.append(
            Paragraph(
                str(data),
                styles["BodyText"],
            )
        )

    elements.append(Spacer(1, 12))


def generate_pdf(
    report: dict,
    version: int,
    output_dir: str = "generated_reports",
):

    os.makedirs(output_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    filename = os.path.join(
        output_dir,
        f"Research_Report_v{version}_{timestamp}.pdf",
    )

    document = SimpleDocTemplate(filename)

    elements = []

    elements.append(
        Paragraph(
            "<b>Research Analysis Report</b>",
            styles["Title"],
        )
    )

    elements.append(Spacer(1, 15))

    elements.append(
        Paragraph(
            f"<b>Research Topic:</b> {report.get('research_topic','')}",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"<b>Total Papers:</b> {report.get('total_papers',0)}",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"<b>Generated By:</b> {report.get('generated_by','')}",
            styles["BodyText"],
        )
    )

    elements.append(
        Paragraph(
            f"<b>Generated At:</b> {report.get('generated_at','')}",
            styles["BodyText"],
        )
    )

    elements.append(Spacer(1, 12))

    add_section(
        elements,
        "Executive Summary",
        report.get("executive_summary", ""),
    )

    add_section(
        elements,
        "Literature Review",
        report.get("literature_review", {}),
    )

    add_section(
        elements,
        "Methodology Comparison",
        report.get("methodology_comparison", {}),
    )

    add_section(
        elements,
        "Research Gap Analysis",
        report.get("research_gap", {}),
    )

    add_section(
        elements,
        "Experiment Plan",
        report.get("experiment_plan", {}),
    )

    add_section(
        elements,
        "Report Summary",
        report.get("report_summary", {}),
    )

    add_section(
        elements,
        "Conclusion",
        report.get("conclusion", ""),
    )

    document.build(elements)

    return filename